version: "3"
services:
    redis:
        image: 'redis:5.0.3'
        restart: always
        hostname: redis
        container_name: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis_data/:/data/
    judge_server1:
        image: hwz634473223/judge_server:local
        restart: always
        depends_on:
          - redis
        tmpfs:
            - /tmp
        volumes: 
            - ./test_cases:/RJudgeServer/test_cases
            - ./submissions:/RJudgeServer/submissions
            - ./judge.log:/RJudgeServer/judge.log
        environment:
            - WEB_SOCKET_URL=ws://192.168.31.129:9502/websocket/judge
            - TOKEN=12345
            - SERVER_URL=192.168.31.129:9501
        tty: true
